Filling values using simpleimputer

In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

In [ ]:
d1=pd.read_csv('/content/menu_items - menu_items.csv')

In [ ]:
d2=pd.read_csv('/content/1 - 1.csv')

In [ ]:
d2.head()

   order_details_id  order_id order_date   order_time  item_id
0                 1         1   01-01-23  11:38:36 AM      109
1                 2         2   01-01-23  11:57:40 AM      108
2                 3         2   01-01-23  11:57:40 AM      124
3                 4         2   01-01-23  11:57:40 AM      117
4                 5         2        NaN          NaN      129

In [ ]:
d1.rename(columns={'menu_item_id':'item_id'},inplace=True)
d1.head()

   item_id      item_name  category  price
0      101      Hamburger  American  12.95
1      102   Cheeseburger  American  13.95
2      103        Hot Dog  American   9.00
3      104  Veggie Burger  American  10.50
4      105   Mac & Cheese  American   7.00

In [ ]:
print(len(d2))
print(len(d1))

32
32

In [ ]:
d3=d1.merge(d2,on='item_id')
d3.head()

,item_id,item_name,category,price,order_details_id,order_id,order_date,order_time
0,101,Hamburger,American,12.95,11,6,01-01-23,12:29:36 PM
1,101,Hamburger,American,12.95,26,11,01-01-23,1:02:59 PM
2,102,Cheeseburger,American,13.95,27,11,01-01-23,1:02:59 PM
3,102,Cheeseburger,American,13.95,28,11,01-01-23,1:02:59 PM
4,102,Cheeseburger,American,13.95,30,12,01-01-23,1:04:41 PM

In [ ]:
d3.isnull().sum()

item_id             0
item_name           0
category            6
price               2
order_details_id    0
order_id            0
order_date          2
order_time          1
dtype: int64

In [ ]:
d3.dtypes

item_id               int64
item_name            object
category             object
price               float64
order_details_id      int64
order_id              int64
order_date           object
order_time           object
dtype: object

In [ ]:
simplemode=SimpleImputer(strategy='most_frequent')

In [ ]:
d3[['category']]=simplemode.fit_transform(d3[['category']])

In [ ]:
d3.isnull().sum()

item_id             0
item_name           0
category            0
price               2
order_details_id    0
order_id            0
order_date          2
order_time          1
dtype: int64

In [ ]:
d3[['order_date']]=simplemode.fit_transform(d3[['order_date']])

In [ ]:
d3[['order_time']]=simplemode.fit_transform(d3[['order_time']])

In [ ]:
simplemean=SimpleImputer(strategy='mean')

In [ ]:
d3[['price']]=simplemean.fit_transform(d3[['price']])

In [ ]:
d3.isnull().sum()

item_id             0
item_name           0
category            0
price               0
order_details_id    0
order_id            0
order_date          0
order_time          0
dtype: int64